### ISSUE TITLE
Private Channel that I own cannot be set or removed

### ISSUE THREAD

**Issue by Swedz** [SuperMartijn642/Tesseract#17] opened 2020-11-06 11:07 UTC
Using version MC 1.12.2 + Tesseract 1.0.13 (latest)

I have a channel, "Battery Input" that I created a while ago that I locked so it's only for my use. Just now I am trying to move my tesseracts around as I'm changing setup. I cannot set my new tesseracts to use that channel, nor can I delete the channel. The channel does show up in the menu, though! I was able to interact with it before. I made new channels, either locked or unlocked, I can interact with them.

I did some investigating for you. My UUID, "a2dca537-693e-4ded-ac4b-c4006dd4d382" has the following bits: -6031511769810939006 (least) and -6711307687281406483 (most). I checked the tesseract channel nbt data in the world file, and these bits match. So that means there's no weird mismatch of UUIDs going on here.

**Comment by SuperMartijn642** [comment] 2020-11-07 13:11
I will do some testing in 1.12 to see if I can replicate the issue. I will probably have more info either later today or tomorrow.

**Comment by SuperMartijn642** [comment] 2020-11-09 13:19
I did found a problem, where after reloading a world, it overrides a previous channel when a new channel is created. This doesn't seem to be related to your issue however.

Do you have access to the save files for the world and if so could you maybe upload them if that's not too much of a hassle?

**Comment by Swedz** [comment] 2020-11-09 21:15
Do you need the entire world file or just the stuff related to tesseract?

**Comment by SuperMartijn642** [comment] 2020-11-09 21:25
The entire world file if you don't mind, because I need the tile entities as well.

**Comment by Swedz** [comment] 2020-11-09 21:39
The world file is pretty large (1.7GB) so I have to upload it to dropbox. It estimates about 40 minutes to upload so I'll comment again here when it's finished.

**Comment by SuperMartijn642** [comment] 2020-11-09 22:33
Ok thank you very much, I will check it tomorrow since it's pretty late for me and I also still have to do school stuff.

**Comment by Swedz** [comment] 2020-11-09 23:18
Here is the link to the [world download](https://www.dropbox.com/s/o9uqlta65h47hua/World.zip?dl=0). Let me know once you've downloaded it so I can take it off my dropbox. This is a backup of before I had to make more channels as a workaround.

**Comment by SuperMartijn642** [comment] 2020-11-10 13:05
I have downloaded the file, thanks for going through the trouble of uploading it!
I will test with the world later today as I should have some free time then.

**Comment by SuperMartijn642** [comment] 2020-11-10 14:14
I changed the UUID in the nbt data to my own so I could interact with the channel. Both on a server and in single player, I can delete the channel without any problem. I also don't see anything out of the ordinary in the nbt data.
Can you still not delete the channel in your world or did the problem go away after a while?
Also, did this issue occur in a single player world or on a server?

**Comment by Swedz** [comment] 2020-11-10 14:15
Ok so something really weird is going on. I wasn't able to delete it before, but I just came back to it and was able to delete it just fine... I have no clue how this could have happened. This is on a multiplayer server.

**Comment by SuperMartijn642** [comment] 2020-11-10 14:20
I'm glad it resolved itself, so at least you don't have to deal with it anymore.
Did it get fixed after you updated to version 1.0.14 perhaps? Maybe that did fix the issue.
It could have been that your channel was sent to your client, but then it was overwritten by someone else's channel, which I fixed in 1.0.14. I thought that was unrelated before, but now that I think about that could have been the problem.

**Comment by Swedz** [comment] 2020-11-10 14:21
Nobody else has used the tesseracts other than me, and I didn't update to 1.0.14 yet.

**Comment by SuperMartijn642** [comment] 2020-11-10 14:28
Ok I will continue to look into the problem with multiple players, to see if I can get something similar to happen.

**Comment by Swedz** [comment] 2020-11-11 00:28
This is probably a different or similar issue, but it just started happening.

Here's my setup first: I have a battery in the overworld, with an input and output. One tesseract directly attached to the input, set to "Store" with Receive Only. Then on the output, one tesseract connected to it by a cryo-stabilized fluxduct (idk, something weird with how the tesseract works it doesnt let it be attached directly to the output and work on ender io capacitors, so adding a fluxduct works) set to "Receive" with Send Only. Then I have my power gen in a different dimension pumping into a tesseract set to "Store" with Send Only. Then in that same dimension I have another tesseract set to "Receive" with Receive Only that powers my farms and stuff. So what is meant to be happening is the power gets generated -> power put into capacitor -> power pumps out into my farms.

The problem is, is my ME system in the overworld is being powered just fine, and so is the battery. However the tesseract in the other dimension set to receive power doesnt actually receive power anymore. This was literally working within 30 minutes ago and I sat here trying to figure out what changed but I can't figure it out as I've been building not messing with my power stuff.

I can send the world again if you need it, but there's a few mods that are required to be able to see the other stuff (ender io, mystcraft, thermal expansion, etc.). 

I'm really unsure why this started happening but this is reminiscent of what was happening before with not being able to use the private channel. Since even though the tesseracts were hooked into the locked channel, it was not working as intended.

**Comment by SuperMartijn642** [comment] 2020-11-11 15:41
Just now, when testing, unrelated to this, I noticed that capacitor banks from Ender IO seem to keep the capabilities of neighboring blocks stored between ticks. Only if the tesseract is broken and replaced, or the input/output settings on the capacitor bank are changed, will the capacitor bank rerequest the capability. Thus, if only the channel on the tesseract is changed the capacitor bank will keep acting as if the old channel is still set, because it still has that capability.
Other mods, such as Thermal Expansion and Mekanism, do request the capability every tick and thus work fine.

I think in your case it might have been the buffer of energy stored in the ME system that ran out whilst you were building. In any case reloading the world should mean the capacitor banks request the capability again and should fix it.

I think this is unrelated from the first issue and this I can reproduce. I will probably fix this issue in the next few days.

As for the first issue, I have been testing on a server with me controlling multiple players and I still haven't been able to replicate it. I am also going through all of the code to optimize it and find potential issues.

**Comment by SuperMartijn642** [comment] 2020-11-13 23:33
In version 1.0.15 I changed a lot of the code and I also noticed that an update packet for the channels wasn't always send when a channel was removed.
I think that might have been the cause of your first issue where you couldn't delete the channel. It would be fixed after a reload of the world, which might be the reason I couldn't replicate it when you send me the world file.

This and some other things are fixed now in version 1.0.15.

I will close the issue for now, thank you for the reports and help in determining the problem. Please let me know if anything else happens by either posting here or creating a new issue. I get an email when a post is made so I will still see it if you post here even though it's closed.

**Closed as completed by SuperMartijn642** 2020-11-13 23:33 UTC
Labels: bug
