### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by tiphilou17** [SuperMartijn642/Tesseract#3] opened 2020-06-05 22:22 UTC
When i connect importer is crash serv...

minecraft 1.15.2
forge latest version

log:
https://gist.github.com/tiphilou17/82a508f55bc2b9bdb119cb292a688527

**Comment by Griefed** [comment] 2020-06-07 14:06
Just a little advise for the future: Don't say "latest version", because if someone were to look at your post in a couple of weeks/months, the latest version would be completely different from the version you actually used/meant. Always be specific with details like these.

OP's Forge version: 31.2.0 (as stated in the log they provided)

**Comment by SuperMartijn642** [comment] 2020-06-30 20:43
I think this has been fixed in 1.0.6, since I can't reproduce it.

**Closed as completed by SuperMartijn642** 2020-06-30 20:43 UTC
Labels: bug
