### ISSUE TITLE
[Feature] Shader support

### ISSUE THREAD

**Issue by Crazyminer34** [SuperMartijn642/Tesseract#103] opened 2024-12-21 02:45 UTC
**Is your feature request related to a problem? Please describe.**
Whenever I use shaders, the end portal shader gets removed, most of the shaders i've tried have custom end portal shaders but they dont work with tesseract

**Describe the solution you'd like**
Find a way to make them compatible or make it use the vanilla shader even when shaders are on

**Comment by Crazyminer34** [comment] 2024-12-21 02:49
https://github.com/SuperMartijn642/Tesseract/issues/88

**Comment by SuperMartijn642** [comment] 2024-12-21 11:45
This seems to be a duplicate of #88, as you have already commented... 🤔

**Closed as completed by SuperMartijn642** 2024-12-21 11:45 UTC
Labels: duplicate, feature request
