### ISSUE TITLE
[Bug] Tesseract Not Working for Items/Fluids/Energy

### ISSUE THREAD

**Issue by castronostra** [SuperMartijn642/Tesseract#77] opened 2023-05-06 04:04 UTC
**Version Info**
- Minecraft, 1.18.2
- Tesseract, 1.0.33

**Description of the Bug**
I am trying to transfer energy wirelessly, but nothing is transferring (including fluids and items). I tried connecting as power source --> Tesseract but nothing was being transferring, Then I tried power source --> power cable --> Tesseract. I'm not getting the ender portal images in the tesseract. Am I doing something wrong?

**Steps to Reproduce**
...

**Screenshots**
![image](https://user-images.githubusercontent.com/132663625/236437036-ce563853-fa9f-47fd-932f-2e194e73b10d.png)
![image](https://user-images.githubusercontent.com/132663625/236437118-378d5b70-ce58-44d3-9162-6e59113754f4.png)

**Comment by SuperMartijn642** [comment] 2023-05-06 16:38
Are you using Fabric or Forge? And what other mod are you trying to transfer power with?

**Comment by castronostra** [comment] 2023-05-06 18:08
I'm using forge. I'm using it with the All the Mods 7: To the Sky modpack. I haven't changed anything about the modpack or the tesseract mod. I just dragged and dropped the mod into the modpacks mod folder.

**Comment by SuperMartijn642** [comment] 2023-05-06 18:24
What other mod are you trying to transfer power with?

**Comment by castronostra** [comment] 2023-05-06 20:25
I'm using thermal series dynamos to generate power and using mekanism energy cells to store the power

**Comment by SuperMartijn642** [comment] 2023-05-07 21:00
Could you check if it works with version 1.0.34?

**Comment by castronostra** [comment] 2023-05-08 18:34
I'll give it shot. I'll give any updates

**Comment by castronostra** [comment] 2023-05-08 20:56
![image](https://user-images.githubusercontent.com/132663625/236931178-ae2b44ed-2cdf-4cee-8de6-f8c60297b098.png)
![image](https://user-images.githubusercontent.com/132663625/236931267-91a6cc91-4f31-45a7-8126-05c697646d4b.png)
![image](https://user-images.githubusercontent.com/132663625/236931411-c1d05b6d-a8df-4a1e-b48d-d9ad1e7fba50.png)

Energy and fluid transfer is working great with mekanism. The mod seems to be intermittent with Flux Networks. Items are still not transferring, however. I am using the latest 1.0.34 and 1.1.7 corelib file for forge. 
I am using the same modpack, and I am trying to transfer items using the Laser IO mod. I am not getting the green laser that I am supposed to see when I insert Laser IO's respective node. I tried using Mekanism's logistical pipes to transfer items as an alternative, but that is not working either.
Personally, this is not a huge setback, since I mainly use the tesseract for energy transfer. Just giving a heads up if anyone is trying to use this mod for item transfer.

**Comment by SuperMartijn642** [comment] 2023-05-08 23:37
Great to hear it is working now.
As for the items, place one of the tesseracts directly against the block you are trying to insert into/extract from. In this case, place the tesseract in the second picture directly against the chest, without the pipe in between.
Pipes themselves don't have an inventory, so when the laser io block tries to insert into the tesseract, it looks for inventories around tesseracts on the same channel and doesn't find anything.

**Comment by castronostra** [comment] 2023-05-09 00:21
Good to know. I'll keep that in mind when I try to transfer items. Thank you for your quick responses!

**Comment by Chayse-Smith** [comment] 2023-05-11 15:36
I'm getting a slightly different issue, but still resulting in energy not flowing.

The Setup:
I'm running a custom mod pack server with a TON of mods (132), and using version 1.0.34 of the tesseract mod, and enderio conduits to transfer RF between a chunk loaded energy source (big reactors reactor) and a non-chunkloaded energy destination (Applied Energistics 2 ME system). I'm usually close enough to the destination that I can say it's usually chunkloaded, but not always.

The Issue:
The energy flows temporarily, and the consistency varies greatly, anywhere from a few seconds to a few days. It has failed while I'm looking at it, and has also continued to work while I've been offline for a day or two. The only thing that seems to be constant, is that when the energy stops flowing, it won't restart itself unless I break the tesseract, place it again, and re-assign the energy channel. I have not tested Item flow.

Comments:
I don't know exactly what introduced the error, if it was a tesseract mod update, or if it's due to a conflict with another mod, or if the server has anything to do with it. I will do some experimenting when I get the time to. What I do know is that I've used older versions of a lot of the same mods in a previous mod pack, and haven't had these issues, so something within the last year or so has introduced the bug.
I'll also upload a logfile if desired with a list of all my mod versions, or anything else you may need.

**Comment by tacogerbil** [comment] 2023-08-12 17:52
Same here.. It's happened several times.   It's insides become transparent out of nowhere when it stops working.  There are no errors.. looked through logs and tesseract doesn't log a thing going wrong at all.  It just stops working.  
Sometimes just breaking the tesseract and replacing it will fix the issue, most of the time not.  Once placed it in a different location and it worked.  I also have a chunk loader a couple blocks away just to make sure.. .  Loading Minecraft 1.19.2 with Fabric Loader 0.14.21, tesseract-1.0.35-fabric-mc1.19.2 .  Usage is transferring Lava for the Create mod and items using Toms simple storage mod.

**Comment by SuperMartijn642** [comment] 2024-12-21 16:36
I fixed a bug now in version 1.0.36 where the data of the last placed tesseract in a save could be overwritten when a new tesseract is placed after loading a save. This would only become visible after then, again, saving and reopening the save.
I assume this is the cause for what was reported here, if anyone still encounters the issue with the updated version, please open a new issue with the appropriate info.
Thank you all for reporting the issue!

**Closed as completed by SuperMartijn642** 2024-12-21 16:36 UTC
Labels: bug
